only check fro missing directories when running a server

diff --git a/bin/server b/bin/server
--- a/bin/server
+++ b/bin/server
@@ -28,12 +28,6 @@ fi
 
 cd $d_main
 
-if [ ! -d bin ] || [ ! -d data ] || [ ! -d script ]
-then
-    echo "Incomplete Instance! bin/, data/ or script/ are missing."
-    exit 1
-fi
-
 ################################################################################
 
 . bin/env.sh
@@ -57,6 +51,12 @@ p_exec() {
 ################################################################################
 
 p_start_server() {
+
+	if [ ! -d bin ] || [ ! -d data ] || [ ! -d script ]
+	then
+		echo "Incomplete Instance! bin/, data/ or script/ are missing."
+		exit 1
+	fi
 
     if [ -p serverexec ]
     then
